services:
  - type: web
    name: passop-backend
    env: node
    plan: free
    buildCommand: cd passop.mongo/passop-backend && npm install
    startCommand: cd passop.mongo/passop-backend && npm start
    domains:
      - passop-backend
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: MONGO_URL
        sync: false
      - key: FRONTEND_URL
        sync: false